default/objects/Lease_Abstract__c/Lease_Abstract__c.object-meta.xml
<CustomObject>
    <description>Used to store the lease abstract tied to the the Due Dillegence Package</description>
    <label>Lease Abstract</label>
    <nameField>
        <label>Lease Abstract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Abstracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Lease_Abstract__c/fields/Current_Monthly_Rent__c.field-meta.xml
<CustomField>
    <fullName>Current_Monthly_Rent__c</fullName>
    <label>Current Monthly Rent</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Divestiture_Site__c.field-meta.xml
<CustomField>
    <fullName>Divestiture_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Divestiture Site</label>
    <referenceTo>Divestiture_Site__c</referenceTo>
    <relationshipLabel>Lease Abstracts</relationshipLabel>
    <relationshipName>Lease_Abstracts</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Divestiture_Site_ID_Text__c.field-meta.xml
<CustomField>
    <fullName>Divestiture_Site_ID_Text__c</fullName>
    <label>Divestiture Site ID (Text)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Holdover__c.field-meta.xml
<CustomField>
    <fullName>Holdover__c</fullName>
    <label>Holdover</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Landlord_Address__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Address__c</fullName>
    <label>Landlord Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Landlord_City__c.field-meta.xml
<CustomField>
    <fullName>Landlord_City__c</fullName>
    <label>Landlord City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Landlord_Email__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Email__c</fullName>
    <label>Landlord Email</label>
    <type>Email</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Landlord_Phone__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Phone__c</fullName>
    <label>Landlord Phone</label>
    <type>Phone</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Landlord_Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Site_ID__c</fullName>
    <label>Landlord Site ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Landlord_State__c.field-meta.xml
<CustomField>
    <fullName>Landlord_State__c</fullName>
    <label>Landlord State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Landlord_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Landlord_Zip_Code__c</fullName>
    <label>Landlord Zip Code</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Lease_ID__c.field-meta.xml
<CustomField>
    <fullName>Lease_ID__c</fullName>
    <label>Lease ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Lease_Landlord__c.field-meta.xml
<CustomField>
    <fullName>Lease_Landlord__c</fullName>
    <label>Lease Landlord</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Lease_Name__c.field-meta.xml
<CustomField>
    <fullName>Lease_Name__c</fullName>
    <label>Lease Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Lease_Status__c.field-meta.xml
<CustomField>
    <fullName>Lease_Status__c</fullName>
    <label>Lease Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Lease_Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Lease_Term_End_Date__c</fullName>
    <label>Lease Term End Date</label>
    <type>Date</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Lease_Use__c.field-meta.xml
<CustomField>
    <fullName>Lease_Use__c</fullName>
    <label>Lease Use</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/MLA__c.field-meta.xml
<CustomField>
    <fullName>MLA__c</fullName>
    <label>MLA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/NNR_Critical_Date__c.field-meta.xml
<CustomField>
    <fullName>NNR_Critical_Date__c</fullName>
    <label>NNR Critical Date</label>
    <type>Date</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/NNR_Reason__c.field-meta.xml
<CustomField>
    <fullName>NNR_Reason__c</fullName>
    <label>NNR Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <label>Payee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Square_Feet_of_Ground_Lease__c.field-meta.xml
<CustomField>
    <fullName>Square_Feet_of_Ground_Lease__c</fullName>
    <inlineHelpText>If applicable</inlineHelpText>
    <label>Square Feet of Ground Lease</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/T_Mo_Unf_Termination_Doc_Section__c.field-meta.xml
<CustomField>
    <fullName>T_Mo_Unf_Termination_Doc_Section__c</fullName>
    <label>T-Mo Unf.Termination Doc Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/T_Mo_Unfet_Modification_Right_Doc__c.field-meta.xml
<CustomField>
    <fullName>T_Mo_Unfet_Modification_Right_Doc__c</fullName>
    <label>T Mo Unfet Modification Right Doc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/T_Mo_Unfet_Modification_Rights__c.field-meta.xml
<CustomField>
    <fullName>T_Mo_Unfet_Modification_Rights__c</fullName>
    <label>T-Mo Unfet Modification Rights</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/T_Mo_Unfet_Termination_Rights__c.field-meta.xml
<CustomField>
    <fullName>T_Mo_Unfet_Termination_Rights__c</fullName>
    <label>T-Mo Unfet Termination Rights</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/T_Mobile_Unfettered_Assig_Right__c.field-meta.xml
<CustomField>
    <fullName>T_Mobile_Unfettered_Assig_Right__c</fullName>
    <label>T-Mobile Unfettered Assig Right</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/T_Mobile_Unfettered_Assig_Right_Doc__c.field-meta.xml
<CustomField>
    <fullName>T_Mobile_Unfettered_Assig_Right_Doc__c</fullName>
    <label>T-Mobile Unfettered Assig Right-Doc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Unres_24_7_Access_Rights_Doc_Sec__c.field-meta.xml
<CustomField>
    <fullName>Unres_24_7_Access_Rights_Doc_Sec__c</fullName>
    <label>Unres 24/7 Access Rights Doc Sec</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

default/objects/Lease_Abstract__c/fields/Unrestricted_24_7_Access_Rights__c.field-meta.xml
<CustomField>
    <fullName>Unrestricted_24_7_Access_Rights__c</fullName>
    <label>Unrestricted 24/7 Access Rights</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

default/classes/TMOS_LeaseAbstractTriggerHandler.cls
/**************************************************************************************************************/
// Purpose: To Upsert Lease_Abstract__c object when a record is inserted in a Lease_Abstract_Update__e Event 
// Registered Callers: TMOS_LeaseAbstractTrigger, TMOS_LeaseAbstractTigger_TEST
// Requirement User Story:
// Date & Developer: 12/30/2020 & BVELU
/**************************************************************************************************************/
public class TMOS_LeaseAbstractTriggerHandler {
    //Map to store SiteName and SiteId for existing Divestiture_Site__c records
    Map<String, Id> mapDivestitureSites = new Map<String, Id>(); 
    //Map to store Lease_ID__c and Id for existing Lease Abstract records
    Map<String, Id> mapLeaseAbstract = new Map<String, Id>(); 
    
    public void processTrigger(List<Lease_Abstract_Update__e> lstOfEvtLeaseAbstractObject){
        System.debug('In to trigger handler');
        System.debug('Total No of Events Received: ' + lstOfEvtLeaseAbstractObject.size());
        if(!lstOfEvtLeaseAbstractObject.isEmpty()){
            List<Lease_Abstract__c> lstLeaseAbstract = new List<Lease_Abstract__c>();
            List<Lease_Abstract__c> insertLeasAbstracts = new List<Lease_Abstract__c>(); // Insert LAs
            Map<Id, Lease_Abstract__c> updateLeaseAbstractsMap = new Map<Id, Lease_Abstract__c>(); //UPdate LAs
            Set<String> setLeaseAbstractIds = new Set<String>(); //Set to store LeaseAbstractId from Trigger.New (lstOfEvtLeaseAbstractObject)
            Set<String> setDivestitureSites = new Set<String>(); //Set to store DivestitureSite Names from Trigger.New (lstOfEvtLeaseAbstractObject)    
            
            //Populate the sets to hold the Divestiture Site Names and Lease_ID from trigger variable.
            for(Lease_Abstract_Update__e evtLeaseAbstract : lstOfEvtLeaseAbstractObject){
                if (evtLeaseAbstract.Lease_ID__c != '' && evtLeaseAbstract.Lease_ID__c != null) {
                    setLeaseAbstractIds.add(evtLeaseAbstract.Lease_ID__c);
                } else {
                    System.debug('Received Lease ID as Blank:' + evtLeaseAbstract);
                }
                if (evtLeaseAbstract.Divestiture_Site_ID_Text__c != '' && evtLeaseAbstract.Divestiture_Site_ID_Text__c != null){
                    setDivestitureSites.add(evtLeaseAbstract.Divestiture_Site_ID_Text__c);                    
                }
            } 
            //Fetch Divestiture SiteId and SiteNames for the set of SiteNames we have in setDivestitureSites and populate the mapDivestitureSites with SiteName and SiteId
            if(!setDivestitureSites.isEmpty()){
                for(Divestiture_Site__c objDS: [Select Id, Name from Divestiture_Site__c where Name IN : setDivestitureSites]){
                    mapDivestitureSites.put(objDS.Name, objDS.Id);
                }
            }
            //Fetch LeaseAbstract Id and Lease_ID__c for the set of Lease_ID__c we have in setLeaseAbstractIds and populate the mapLeaseAbstract with  Id and Lease_ID__c
            if(!setLeaseAbstractIds.isEmpty()){
                for(Lease_Abstract__c objLARef :  [Select Id, Lease_ID__c from Lease_Abstract__c where Lease_ID__c IN : setLeaseAbstractIds]){
                    mapLeaseAbstract.put(objLARef.Lease_ID__c, objLARef.Id);
                }
            }
            //Create Lease_Abstract__c object instance map the values from the Event object. 
            //Populate the Divestriture SiteId and LeaseAbstractId for existing objects from the Map and Bulkify the lstLeaseAbstract to upsert
            for(Lease_Abstract_Update__e evtLeaseAbstract : lstOfEvtLeaseAbstractObject){
                if (mapEventToObject(evtLeaseAbstract).Id == null) {
                    insertLeasAbstracts.add(mapEventToObject(evtLeaseAbstract));
                } else {
                    updateLeaseAbstractsMap.put(mapEventToObject(evtLeaseAbstract).Id, mapEventToObject(evtLeaseAbstract)); 
                }
            }
            
            //Insert LAs
            if (insertLeasAbstracts.size() > 0) {
                try{
                    insert insertLeasAbstracts;
                } catch(DmlException e) {
                    System.debug('DML Exception Occured Insert: ' + e.getMessage());
                    insertLog('DML Exception Occured Insert: ' + e.getMessage(), lstOfEvtLeaseAbstractObject.size(), insertLeasAbstracts.size(), updateLeaseAbstractsMap.size());
                } 
            }
            
            //Update LAs
            if (updateLeaseAbstractsMap.size() > 0) {
                try {
                    update updateLeaseAbstractsMap.values();
                } catch(DmlException e) {
                    System.debug('DML Exception Occured Update: ' + e.getMessage());
                    insertLog('DML Exception Occured Update: ' + e.getMessage(), lstOfEvtLeaseAbstractObject.size(), insertLeasAbstracts.size(), updateLeaseAbstractsMap.size() );
                }  
            }           
            //Insert Success message
            System.debug('Records Received: '+ lstOfEvtLeaseAbstractObject.size() + ' Updated: ' + updateLeaseAbstractsMap.size() + ' Inserted: ' + insertLeasAbstracts.size());
            insertLog('Records Received: '+ lstOfEvtLeaseAbstractObject.size() + ' Updated: ' + updateLeaseAbstractsMap.size() + ' Inserted: ' + insertLeasAbstracts.size(), lstOfEvtLeaseAbstractObject.size(), insertLeasAbstracts.size(), updateLeaseAbstractsMap.size() );
        }
    }
    public Lease_Abstract__c mapEventToObject(Lease_Abstract_Update__e evtLeaseAbstract){
        Lease_Abstract__c objLA = new Lease_Abstract__c();
        //Map Id to field to existing Lease Record, if found
        if(!mapLeaseAbstract.isEmpty()){
            if (mapLeaseAbstract.containsKey(evtLeaseAbstract.Lease_ID__c)) {                
                objLA.Id = mapLeaseAbstract.get(evtLeaseAbstract.Lease_ID__c);                                                
            } else {
                objLA.Name = evtLeaseAbstract.Divestiture_Site_ID_Text__c + '_LA';   
            }   
        }  else {
            objLA.Name = evtLeaseAbstract.Divestiture_Site_ID_Text__c + '_LA';
        }     
        
        objLA.Lease_ID__c = evtLeaseAbstract.Lease_ID__c;
        if(evtLeaseAbstract.Current_Monthly_Rent__c != null){
            objLA.Current_Monthly_Rent__c = evtLeaseAbstract.Current_Monthly_Rent__c / 12;
        }
        
        if (!mapDivestitureSites.isEmpty()){
            if (mapDivestitureSites.containsKey(evtLeaseAbstract.Divestiture_Site_ID_Text__c)) {  
                objLA.Divestiture_Site__c = mapDivestitureSites.get(evtLeaseAbstract.Divestiture_Site_ID_Text__c);  
            }
        }
        objLA.Divestiture_Site_ID_Text__c = evtLeaseAbstract.Divestiture_Site_ID_Text__c; // Discuss with PK
        objLA.Holdover__c = evtLeaseAbstract.Holdover__c;
        //Map Landlord details
        objLA.Landlord_Address__c = evtLeaseAbstract.Landlord_Address__c;
        objLA.Landlord_City__c = evtLeaseAbstract.Landlord_City__c;
        if (evtLeaseAbstract.Landlord_Email__c != null && evtLeaseAbstract.Landlord_Email__c != ''){
            if (checkEmail(evtLeaseAbstract.Landlord_Email__c)) {
                objLA.Landlord_Email__c = evtLeaseAbstract.Landlord_Email__c;
            }           
        }
        objLA.Landlord_Phone__c = evtLeaseAbstract.Landlord_Phone__c;
        objLA.Landlord_Site_ID__c = evtLeaseAbstract.Landlord_Site_ID__c;
        objLA.Landlord_State__c = evtLeaseAbstract.Landlord_State__c;
        objLA.Landlord_Zip_Code__c = evtLeaseAbstract.Landlord_Zip_Code__c;
        //Map Lease details
        objLA.Lease_Landlord__c = evtLeaseAbstract.Lease_Landlord__c;
        objLA.Lease_Name__c = evtLeaseAbstract.Lease_Name__c;
        objLA.Lease_Status__c = evtLeaseAbstract.Lease_Status__c;
        objLA.Lease_Term_End_Date__c = evtLeaseAbstract.Lease_Term_End_Date__c;
        objLA.Lease_Use__c = evtLeaseAbstract.Lease_Use__c;
        objLA.MLA__c = evtLeaseAbstract.MLA__c;
        //objLA.MLA_ID_C__c = evtLeaseAbstract.MLA_ID_C__c; ?
        objLA.NNR_Critical_Date__c = evtLeaseAbstract.NNR_Critical_Date__c;
        objLA.NNR_Reason__c = evtLeaseAbstract.NNR_Reason__c;
        objLA.Payee__c = evtLeaseAbstract.Payee__c;
        objLA.Square_Feet_of_Ground_Lease__c = evtLeaseAbstract.Square_Feet_of_Ground_Lease__c;
        objLA.T_Mobile_Unfettered_Assig_Right__c = evtLeaseAbstract.T_Mobile_Unfettered_Assig_Right__c;
        objLA.T_Mobile_Unfettered_Assig_Right_Doc__c = evtLeaseAbstract.T_Mobile_Unfettered_Assig_Right_Doc__c;
        objLA.T_Mo_Unfet_Modification_Right_Doc__c = evtLeaseAbstract.T_Mo_Unfet_Modification_Right_Doc__c;
        objLA.T_Mo_Unfet_Modification_Rights__c = evtLeaseAbstract.T_Mo_Unfet_Modification_Rights__c;
        objLA.T_Mo_Unfet_Termination_Rights__c = evtLeaseAbstract.T_Mo_Unfet_Termination_Rights__c;
        objLA.T_Mo_Unf_Termination_Doc_Section__c = evtLeaseAbstract.T_Mo_Unf_Termination_Doc_Section__c;
        objLA.Unres_24_7_Access_Rights_Doc_Sec__c = evtLeaseAbstract.Unres_24_7_Access_Rights_Doc_Sec__c;
        objLA.Unrestricted_24_7_Access_Rights__c = evtLeaseAbstract.Unrestricted_24_7_Access_Rights__c;
        return objLA;
    }
    public void insertLog(String sErrorText, Integer totalEventsReceived, Integer totalEventsInserted, Integer totalEventsUpdated){
        Platform_Event_Log__c objLog = new Platform_Event_Log__c();
        objLog.Event_Name__c = 'Lease_Abstract_Update__e';
        objLog.Name = 'Lease Abstract: ' + String.valueOf(datetime.now());
        objLog.Process_Date__c = date.today();
        objLog.Total_No_of_Event_Received__c = totalEventsReceived;
        objLog.Total_No_of_Events_Inserted__c = totalEventsInserted;
        objLog.Total_No_of_Events_Updated__c = totalEventsUpdated;
        objLog.Message__c = sErrorText;
        insert objLog;
    }
    
    public  Boolean checkEmail(String sEmail) {
        Boolean returnValue = true;
        String InputEmail = sEmail;
        String emailRegex = '([a-zA-Z0-9_\\-\\.]+)@((\\[a-z]{1,3}\\.[a-z]{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})';  
        Pattern MyPattern = Pattern.compile(emailRegex);
        Matcher MyMatcher = MyPattern.matcher(InputEmail);
        if (!MyMatcher.matches()) {
            returnValue = false;
        }
        return returnValue;    
    }  
}